core/urls.py
from django.urls import path
from .views import (
    add_to_cart, CheckoutView, remove_from_cart,
    remove_single_item_from_cart,
    HomeView, ItemDetailView, OrderSummaryView,
    PaymentView
)
import string

app_name = 'core'

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('products/<slug>/', ItemDetailView.as_view(), name='products'),
    path('add-to-cart/<slug>', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
]

ecommerce_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django_countries.fields import CountryField

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport Wear'),
    ('OW', 'Outwear'),
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
)



class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(max_length=2, choices=CATEGORY_CHOICES)
    label = models.CharField(max_length=1, choices=LABEL_CHOICES)
    slug = models.SlugField()
    description = models.TextField()
   

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('core:products', kwargs={
            'slug': self.slug
        })
    
    def get_add_to_cart_url(self):
        return reverse('core:add-to-cart', kwargs={
            'slug': self.slug,
        })
    
    def get_remove_from_cart_url(self):
        return reverse('core:remove-from-cart', kwargs={
            'slug':self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE,
    )
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.quantity} of {self.item.title}'

    def get_total_price(self):
        return self.quantity*self.item.price
    
    def get_total_discount_price(self):
        return self.quantity*self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_price()-self.get_total_discount_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_price()
        return self.get_total_price()


class Order(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE
    )
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey(
        'BillingAddress', 
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


class BillingAddress(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE
    )
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=True)
    zip = models.CharField(max_length=100)
    

    def __str__(self):
        return self.user.username

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <style type="text/css">
        html,
        body,
        header,
        .carousel {
          height: 60vh;
        }
    
        @media (max-width: 740px) {
    
          html,
          body,
          header,
          .carousel {
            height: 100vh;
          }
        }
    
        @media (min-width: 800px) and (max-width: 850px) {
    
          html,
          body,
          header,
          .carousel {
            height: 100vh;
          }
        }
      </style>
    <title>{% block head_title %}{% endblock head_title %}</title>
    {% block extra_head %}
    {% endblock extra_head %}
</head>

{% include 'navbar.html' %}  


<body>
    <div class="mt-5 pt-3">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dissmissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content  %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock extra_body %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}

    {% include 'scripts.html' %}
    {% include 'footer.html' %}
</body>
</html>

templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content  %}

<body class="grey lighten-3">
    <!--Main layout-->
    <main>
        <div class="container wow fadeIn">

            <!-- Heading -->
            <h2 class="my-5 h2 text-center">Checkout form</h2>

            <!--Grid row-->
            <div class="row">

                <!--Grid column-->
                <div class="col-md-8 mb-4">

                    <!--Card-->
                    <div class="card">

                        <!--Card content-->
                        <form method="POST" class="card-body">
                        {% csrf_token %}

                            <!-- <form method="POST" action="">
                                {%  csrf_token %}
                                {{ form|crispy }}
                                <button type="submit" class="btn btn-primary">Checkout</button>
                            </form> -->

                            <!--address-->
                            <div class="md-form mb-5">
                                <!-- <input type="text" id="address" class="form-control" placeholder="1234 Main St"> -->
                                {{ form.street_address }}
                                <label for="address">Address</label>
                            </div>

                            <!--address-2-->
                            <div class="md-form mb-5">
                                <!-- <input type="text" id="address-2" class="form-control" placeholder="Apartment or suite"> -->
                                {{ form.apartment_address }}
                                <label for="address-2">Address 2 (optional)</label>
                            </div>

                            <!--Grid row-->
                            <div class="row">

                                <!--Grid column-->
                                <div class="col-lg-4 col-md-12 mb-4">

                                    <label for="country">Country</label>
                                    <!-- <select class="custom-select d-block w-100" id="country" required>
                                        <option value="">Choose...</option>
                                        <option>United States</option>
                                    </select> -->
                                    {{ form.country }}
                                    <div class="invalid-feedback">
                                        Please select a valid country.
                                    </div>

                                </div>
                                <!--Grid column-->


                                <!--Grid column-->
                                <div class="col-lg-4 col-md-6 mb-4">

                                    <label for="zip">Zip</label>
                                    <!-- <input type="text" class="form-control" id="zip" placeholder="" required> -->
                                    {{ form.zip }}
                                    <div class="invalid-feedback">
                                        Zip code required.
                                    </div>

                                </div>
                                <!--Grid column-->

                            </div>
                            <!--Grid row-->

                            <hr>

                            <div class="custom-control custom-checkbox">
                                <input {% if form.same_billing_address.value %} checked {% endif %} type="checkbox" class="custom-control-input" id="same-address">
                                <label class="custom-control-label" for="same-address">
                                    Shipping address is the same as my billing address
                                </label>
                            </div>
                            <div class="custom-control custom-checkbox">
                                <input {% if form.save_info.value %} checked {% endif %} type="checkbox" class="custom-control-input" id="save-info">
                                <label class="custom-control-label" for="save-info">
                                    Save this information for next time
                                </label>
                            </div>

                            <hr>

                            <div class="d-block my-3">
                                {% for value, name in form.fields.payment_option.choices %}
                                <div class="custom-control custom-radio">
                                    <input value="{{ value }}" id="{{ name }}" name="payment_option" type="radio" class="custom-control-input" required>
                                    <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                                </div>
                                {% endfor %}
                                <!-- <div class="custom-control custom-radio">
                                    <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input"
                                        required>
                                    <label class="custom-control-label" for="paypal">Paypal</label>
                                </div> -->
                                
                            </div>


                            <hr class="mb-4">
                            <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

                        </form>

                    </div>
                    <!--/.Card-->

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-4 mb-4">

                    <!-- Heading -->
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted">Your cart</span>
                        <span class="badge badge-secondary badge-pill">3</span>
                    </h4>

                    <!-- Cart -->
                    <ul class="list-group mb-3 z-depth-1">
                        <li class="list-group-item d-flex justify-content-between lh-condensed">
                            <div>
                                <h6 class="my-0">Product name</h6>
                                <small class="text-muted">Brief description</small>
                            </div>
                            <span class="text-muted">$12</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between lh-condensed">
                            <div>
                                <h6 class="my-0">Second product</h6>
                                <small class="text-muted">Brief description</small>
                            </div>
                            <span class="text-muted">$8</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between lh-condensed">
                            <div>
                                <h6 class="my-0">Third item</h6>
                                <small class="text-muted">Brief description</small>
                            </div>
                            <span class="text-muted">$5</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between bg-light">
                            <div class="text-success">
                                <h6 class="my-0">Promo code</h6>
                                <small>EXAMPLE CODE</small>
                            </div>
                            <span class="text-success">-$5</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between">
                            <span>Total (USD)</span>
                            <strong>$20</strong>
                        </li>
                    </ul>
                    <!-- Cart -->

                    <!-- Promo code -->
                    <form class="card p-2">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Promo code"
                                aria-label="Recipient's username" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
                            </div>
                        </div>
                    </form>
                    <!-- Promo code -->

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

        </div>
    </main>
    <!--Main layout-->
</body>
{% endblock content %}

templates/home-page.html
{% extends 'base.html' %}

{% block content  %}
  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">


        <div class="row wow fadeIn">

          {% for item in items %}
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">
              <!--Card image-->
              <div class="view overlay">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"
                  alt="">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>
                <h4 class="font-weight-bold blue-text">
                  <strong>
                    {% if item.discount_price %}
                    {{ item.discount_price }}$
                    {% else %}
                    {{ item.price }}$
                    {% endif %}
                </strong>
                </h4>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>


      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>


          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <!--Pagination-->
      {% endif %}
    </div>
  </main>
  <!--Main layout-->
{% endblock content %}

templates/navbar.html
  {% load cart_template_tags %}
  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
      <div class="container">

          <!-- Brand -->
          <a class="navbar-brand waves-effect" href="{% url 'core:home' %}" target="_blank">
              <strong class="blue-text">Django E-commerce</strong>
          </a>

          <!-- Collapse -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>

          <!-- Links -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">

              <!-- Left -->
              <ul class="navbar-nav mr-auto">
                  <li class="nav-item">
                      <a class="nav-link waves-effect" href="{% url 'core:home' %}">Home
                          <span class="sr-only">(current)</span>
                      </a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link waves-effect" href="{% url 'core:checkout' %}" target="_blank">Checkout</a>
                  </li>
              </ul>

              <!-- Right -->
              <ul class="navbar-nav nav-flex-icons">
                  {% if request.user.is_authenticated %}
                  <li class="nav-item">
                      <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
                          <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                          <i class="fas fa-shopping-cart"></i>
                          <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                      </a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'account_logout' %} " class="nav-link waves-effect">
                        <span class="clearfix d-none d-sm-inline-block"> Logout </span>
                    </a>
                </li>
                  {% else %}
                  <li class="nav-item">
                      <a href="{% url 'account_login' %}" class="nav-link waves-effect">
                          <span class="clearfix d-none d-sm-inline-block"> Sign In </span>
                      </a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'account_signup' %}" class="nav-link waves-effect">
                        <span class="clearfix d-none d-sm-inline-block"> Sign Up </span>
                    </a>
                </li>
                  {% endif %}
              </ul>

          </div>

      </div>
  </nav>
  <!-- Navbar -->

templates/order-summary.html
{% extends 'base.html' %}

{% block content  %}
<!--Main layout-->
<main>
    <div class="container">

        <div class="table-responsive">
            <h2 class="mt-3">Order Summary</h2>
            <table class="table">
                <thead>
                    <tr>

                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Price</th>

                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <!-- title -->
                        <td>{{ order_item.item.title }}</td>

                        <!-- item price -->
                        {% if order_item.item.discount_price %}
                            <td>
                                <del>${{ order_item.item.price}}</del>
                                ${{ order_item.item.discount_price }}
                            </td> 
                        {% else %}
                            <td>${{ order_item.item.price}}</td>
                        {% endif %}
                        
                        <!-- item quantity -->
                        <td>
                            <!-- remove single item from cart -->
                            <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-angle-down mr-1"></i></a>
                            {{ order_item.quantity }}
                            <!-- add single item to cart -->
                            <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-angle-up ml-1"></i></a>
                        </td>

                        <!-- item total price with or without discount -->
                        <td>
                            {% if order_item.item.discount_price %}
                                ${{ order_item.get_total_discount_price }}
                                <span class="badge badge-danger">
                                    Saving ${{ order_item.get_amount_saved }}
                                </span>
                            {% else %}
                                ${{ order_item.get_total_price }}
                            {% endif %}
                            <a href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                                <i class="fas fa-trash-alt float-right"></i>
                            </a>
                        </td>
                    </tr>

                    {% empty %}
                    <tr>
                        <td colspan="5">Your cart is empty</td>
                        <td colspan="5">
                            <a class="btn btn-primary float-right " href="{% url 'core:home' %}">
                                Continue shoping
                            </a>
                        </td>
                    </tr>

                    {% endfor %}
                    {% if object.get_total %}
                    <tr>
                        <td colspan="4"><b>Order Total</b></td>
                        <td>
                            <b>${{ object.get_total }}</b>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class="btn btn-warning float-right ml-2" href="{% url 'core:checkout' %}">
                                Proceed to checkout
                            </a>
                            <a class="btn btn-primary float-right " href="{% url 'core:home' %}">
                                Continue shoping
                            </a>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>


    </div>
</main>
<!--Main layout-->
{% endblock content %}

templates/product-page.html
{% extends 'base.html' %}

{% block content  %}
<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

        <!--Grid row-->
        <div class="row wow fadeIn">

            <!--Grid column-->
            <div class="col-md-6 mb-4">

                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid"
                    alt="">

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6 mb-4">

                <!--Content-->
                <div class="p-4">

                    <div class="mb-3">
                        <a href="">
                            <span class="badge purple mr-1">{{ item.get_category_display }}</span>
                        </a>
                    </div>

                    <p class="lead">
                        <strong>
                            {% if item.discount_price %}
                            <span class="mr-1">
                                <del>{{item.price}}$</del>
                            </span>
                            <span class="mr-1">
                                {{ item.discount_price }}$
                            </span>
                            {% else %}
                            <span class="mr-1">
                                {{ item.price }}$
                            </span>
                            {% endif %}
                        </strong>
                    </p>

                    <p class="lead font-weight-bold">Description</p>

                    <p>{{ item.description }}</p>
                    <!-- 
            
           <form class="d-flex justify-content-left">
                <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
                <button class="btn btn-primary btn-md my-0 p" type="submit">
                  Add to cart
                  <i class="fas fa-shopping-cart ml-1"></i>
                </button>
            </form> -->

                    <a href=" {{ item.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
                        Add to cart
                        <i class="fas fa-shopping-cart ml-1"></i>
                    </a>
                    <a href=" {{ item.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
                        Remove from cart
                    </a>


                </div>
                <!--Content-->

            </div>
            <!--Grid column-->

        </div>
        <!--Grid row-->

        <hr>

        <!--Grid row-->
        <div class="row d-flex justify-content-center wow fadeIn">

            <!--Grid column-->
            <div class="col-md-6 text-center">

                <h4 class="my-4 h4">Additional information</h4>

                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta
                    odit
                    voluptates,
                    quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

            </div>
            <!--Grid column-->

        </div>
        <!--Grid row-->

        <!--Grid row-->
        <div class="row wow fadeIn">

            <!--Grid column-->
            <div class="col-lg-4 col-md-12 mb-4">

                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid"
                    alt="">

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4">

                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid"
                    alt="">

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4">

                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid"
                    alt="">

            </div>
            <!--Grid column-->

        </div>
        <!--Grid row-->

    </div>
</main>
<!--Main layout-->
{% endblock content %}

templates/scripts.html
{% load static %}
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<script type="text/javascript">
  // Animations initialization
  new WOW().init();
</script>